### PR TITLE
Migrate to Wedeploy beta

### PR DESCRIPTION
**Pull request by jonnilundy**
I wrote this assuming the project would be named "metaljschat" (if not, you will need to change the URL for the stylesheet". Let me know if it needs any changes.

Tested her: https://nodeapp-slackin.wedeploy.io/

### CODE REVIEW

**Comment by pragmaticivan** [comment]
The previous one was `https://metaljs-chat.wedeploy.io/`, if we change the service url, we would need to open a PR on https://github.com/metal/metal.js too to update the README.

**Comment by jonnilundy** [comment]
I think the URL needs to be changed either way, unless we want the project ID to be "chat" and then the node service to be "metaljs". That seems a bit weird to me. If you are okay with proceeding, I can create a pr over there.

**Comment by pragmaticivan** [comment]
I'm ok with that your change. LGTM :) maybe someone else can give some feedback too. Or maybe it's a good time to have `https://chat.metaljs.com` in place as a custom domain.

**Comment by jonnilundy** [comment]
@zenorocha @Robert-Frampton do you have any thoughts?

**Comment by zenorocha** [comment]
LGTM

**Pull request merged**
